<script setup>
import { TrendingUp, TrendingDown } from 'lucide-vue-next'
defineProps({ report: { type: Object, required: true } })
</script>

<template>
  <!-- Styled to read like a printable PDF page -->
  <div class="mx-auto max-w-xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
    <div class="flex items-center justify-between border-b border-slate-100 pb-4">
      <div class="flex items-center gap-2">
        <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-sm font-bold text-white">R</div>
        <span class="text-sm font-semibold text-slate-700">Revenue Report</span>
      </div>
      <span class="text-xs text-slate-400">{{ report.generatedAt }}</span>
    </div>

    <div class="mt-4">
      <h2 class="text-lg font-bold text-slate-900">{{ report.propertyName }}</h2>
      <p class="text-xs text-slate-500">Prepared for {{ report.ownerName }} · {{ report.period }}</p>
    </div>

    <div class="mt-4 grid grid-cols-4 gap-2">
      <div v-for="k in report.kpis" :key="k.label" class="rounded-lg bg-slate-50 p-2.5 text-center">
        <p class="text-[10px] font-medium uppercase text-slate-400">{{ k.label }}</p>
        <p class="mt-0.5 text-sm font-bold text-slate-800">{{ k.value }}</p>
        <p
          class="mt-0.5 inline-flex items-center gap-0.5 text-[10px] font-semibold"
          :class="k.delta >= 0 ? 'text-emerald-600' : 'text-rose-600'"
        >
          <component :is="k.delta >= 0 ? TrendingUp : TrendingDown" class="h-2.5 w-2.5" />
          {{ k.delta >= 0 ? '+' : '' }}{{ k.delta }}%
        </p>
      </div>
    </div>

    <div class="mt-5">
      <h3 class="text-xs font-semibold uppercase tracking-wide text-slate-400">Actions taken this period</h3>
      <ul class="mt-2 space-y-1.5">
        <li v-for="(a, i) in report.actionsTaken" :key="i" class="flex items-start gap-2 text-sm text-slate-600">
          <span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-500" />{{ a }}
        </li>
      </ul>
    </div>

    <div class="mt-5">
      <h3 class="text-xs font-semibold uppercase tracking-wide text-slate-400">Outlook</h3>
      <p class="mt-1.5 text-sm leading-relaxed text-slate-600">{{ report.outlook }}</p>
    </div>

    <div class="mt-6 border-t border-slate-100 pt-3 text-center text-[10px] text-slate-300">
      Generated by Revenue Assistant · GuestPro
    </div>
  </div>
</template>
